### ISSUE TITLE
Not working as of 16.01.2015

### ISSUE THREAD

**Issue by skrat** [ejci/nepi-jano#16]
$subj

**Comment by ejci** [comment]
As far I know its working. Whats the article where its not working and whats the version you have?

**Comment by zemiak** [comment]
http://www.sme.sk/c/7594133/harabin-taji-ci-ako-sef-dostaval-od-sudcov-desiatky.html

-->

Vážení čitatelia,
od 16. januára 2015 sme ukončili prevádzku tejto verzie aplikácie SME.sk.
Ak chcete aplikáciu naďalej používať, prosíme vás o aktualizáciu na novú verziu

**Comment by timelordx** [comment]
Make sure you're running the latest version, which is 0.10.0 at this moment. Version 0.9.7 doesn't work anymore. As soon as I have upgraded to 0.10.0, everything's back to business.

**Comment by skrat** [comment]
my :hankey: 0.10 works, thanks
