### ISSUE TITLE
Maintenance request

### ISSUE THREAD

**Issue by viliampucik** [ejci/nepi-jano#25]
Please may I officially take maintenance of this add-on using my fork https://github.com/viliampucik/nepi-jano?

**Comment by ejci** [comment]
Feel free to do whatever you need with your fork.

**Comment by ejci** [comment]
Btw we are looking for developers (fe, backend,...) in booking.com ;)
If you are interested let me know.

**Comment by viliampucik** [comment]
Nice :) May I ask you to modify your nepi-jano project home page to forward users to my fork (https://github.com/viliampucik/nepi-jano) to obtained the updated and maintained extensions?

**Comment by viliampucik** [comment]
Including @SelfMan, @athelas64, @Dehumanizer77, and @risototh.

**Comment by ejci** [comment]
done
