### ISSUE TITLE
Not working right now

### ISSUE THREAD

**Issue by Dehumanizer77** [ejci/nepi-jano#26]
nepi-jano stopped working about a week ago. Since it still works if you load the s.sme.sk with the article ID manually, I suppose just a small and simple fix will be enough to get it working again.

**Comment by ejci** [comment]
Im not maintaining this extension anymore. I stopped doing that longer time ago. There is one fork that is maintained (https://github.com/viliampucik/nepi-jano). Try to poke maintainer of that fork.
