### ISSUE TITLE
10 second meta refresh on opening links

### ISSUE THREAD

**Issue by nekromoff** [ejci/nepi-jano#27]
Links first open to 10 second meta refresh on sme.sk, after that full page is displayed.

**Comment by ejci** [comment]
Im not supporting this extension anymore. There is a active fork of this repo here [viliampucik/nepi-jano](https://github.com/viliampucik/nepi-jano).

I suggest that you pay for subscription if you want to use service though. I guess you would like to be also paid for your job at [Pizza SEO](https://pizzaseo.com/).

**Comment by nekromoff** [comment]
Funny that you mention that, since you have actually developed this in the
first place :-) allowing users to circumvent paying service.

I have a subscription to another service that is good enough for me and
rarely use this. But I have recently used that and found this bug. Fair
enough, it's not developed anymore.

Thanks for the link, BTW.
