### ISSUE TITLE
zacykleny refresh

### ISSUE THREAD

**Issue by Jispry** [ejci/nepi-jano#28]
ked si ovorim uzamknuty clanok tak broswer zacykli v refreshoch.
skuste napr. https://plus.sme.sk/c/20443930/koho-si-zralok-vybral-nemal-sancu-tvrdi-veteran-z-lode-uss-indianapolis.html

**Comment by viliampucik** [comment]
Je mi luto, dane rozsirenie si treba odinstalovat, pretoze bezplatne prezeranie clankov uz nie je dalej podporovane zo strany SME (https://github.com/viliampucik/nepi-jano/).

**Comment by agiertli** [comment]
Takže toto znamená oficiálne koniec nepi-jano ? :-(
Nie je možný žiadny technický workaround?
